### PR TITLE
No empty catch block

### PR DESCRIPTION
**Pull request by jsf9k**
These are some minimal changes to make LGTM and flake8 happy.

### CODE REVIEW

**Comment by jsf9k** [comment]
This pull request **fixes 4 alerts** when merging cd1ab808def5892ca675c7e192438395ca82d3a8 into 2b613d0a45f2207b2c998ea1290cee35b0a32860 - [view on LGTM.com](https://lgtm.com/projects/g/cisagov/saver/rev/pr-69b73865c0861917424a4e42fd17730d53d587c6)

**fixed alerts:**

* 4 for Except block handles &#39;BaseException&#39;

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jsf9k** [comment]
This pull request **fixes 4 alerts** when merging 87d2ae62766c13aace80d7294a522f4967f9737f into 2b613d0a45f2207b2c998ea1290cee35b0a32860 - [view on LGTM.com](https://lgtm.com/projects/g/cisagov/saver/rev/pr-d8fa801ff682a771ea549d57efab66778371f59c)

**fixed alerts:**

* 4 for Except block handles &#39;BaseException&#39;

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Review by dav3r — APPROVED** [review]
Nice and shiny. 💎

**Comment by jsf9k** [comment]
I think the words you're looking for are "shiny and chrome."

**Pull request merged**
