### PR TITLE
Rework for new fields

### PR DESCRIPTION
**Pull request by jsf9k**
cisagov/pshtt#179, cisagov/trustymail#110, and 18F/domain-scan#286 introduce some new fields into the `domain-scan` output.  As a step toward handling these new fields, I am updating the saving code to use a [`csv.DictReader`](https://docs.python.org/3.6/library/csv.html#csv.DictReader) instead of plain old [`csv.reader`](https://docs.python.org/3.6/library/csv.html#csv.reader).  This change means that we can reference the fields in the `domain-scan` CSVs by their name instead of numerical index.  This is cleaner and more maintainable (and certainly less prone to error).

Note that this PR does not contain code to handle the new fields, it just paves the way to make it easier to do so.

I also took the opportunity to fix a lot of flake8 warnings and [update the `yaml.load()` calls to get rid of a deprecation warning](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation).

### CODE REVIEW

**Comment by jsf9k** [comment]
This pull request **fixes 5 alerts** when merging e1d4c669965c00ade9af3f792d12fce393376b02 into a12619188a95598c2918baa013122f90a29a958b - [view on LGTM.com](https://lgtm.com/projects/g/cisagov/saver/rev/pr-622f0506cfff00baf48c0d56ac6d3c7593fab8df)

**fixed alerts:**

* 5 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Review by dav3r — APPROVED** [review]
Look at Mr. Proactive over here!  Seriously though, this is a very nice improvement. 🥇

**Comment by jsf9k** [comment]
It's not as proactive as you think, since I needed to change this code anyway to test those three PRs (which I am in the midst of doing).

**Comment by jsf9k** [comment]
This can be merged once cisagov/pshtt#179, cisagov/trustymail#110, and 18F/domain-scan#286 are merged.  My testing with a full scan run gave the same results as last weekend's run, except for correctly handling HTTPS sites that require client certs.

**Pull request merged**
